import {
  APPOINTMENT_NOTIFICATIONS_APP_NAME,
  CUSTOMER_EMAIL_NOTIFICATION_APP_NAME,
  CUSTOMER_TEXT_MESSAGE_NOTIFICATION_APP_NAME,
} from "./apps";

export const PreinstalledApps: Record<string, string> = {
  [CUSTOMER_EMAIL_NOTIFICATION_APP_NAME]: CUSTOMER_EMAIL_NOTIFICATION_APP_NAME,
  [CUSTOMER_TEXT_MESSAGE_NOTIFICATION_APP_NAME]:
    CUSTOMER_TEXT_MESSAGE_NOTIFICATION_APP_NAME,
  [APPOINTMENT_NOTIFICATIONS_APP_NAME]: APPOINTMENT_NOTIFICATIONS_APP_NAME,
};
