import { DateTime, DateTimeFormatOptions } from "luxon";

export type DateTimeFormat =
  | "DATETIME_FULL"
  | "DATETIME_HUGE"
  | "DATETIME_MED"
  | "DATETIME_SHORT"
  | "DATETIME_MED_WITH_WEEKDAY"
  | "DATE_FULL"
  | "DATE_HUGE"
  | "DATE_MED"
  | "DATE_SHORT"
  | "DATE_MED_WITH_WEEKDAY"
  | "TIME_24_SIMPLE"
  | "TIME_SIMPLE"
  | "TIME_24_WITH_SECONDS"
  | "TIME_WITH_SECONDS";

export const DATE_TIME_FORMATS: Record<DateTimeFormat, DateTimeFormatOptions> =
  {
    DATETIME_FULL: DateTime.DATETIME_FULL,
    DATETIME_HUGE: DateTime.DATETIME_HUGE,
    DATETIME_MED: DateTime.DATETIME_MED,
    DATETIME_SHORT: DateTime.DATETIME_SHORT,
    DATETIME_MED_WITH_WEEKDAY: DateTime.DATETIME_MED_WITH_WEEKDAY,
    DATE_FULL: DateTime.DATE_FULL,
    DATE_HUGE: DateTime.DATE_HUGE,
    DATE_MED: DateTime.DATE_MED,
    DATE_SHORT: DateTime.DATE_SHORT,
    DATE_MED_WITH_WEEKDAY: DateTime.DATE_MED_WITH_WEEKDAY,
    TIME_24_SIMPLE: DateTime.TIME_24_SIMPLE,
    TIME_SIMPLE: DateTime.TIME_SIMPLE,
    TIME_24_WITH_SECONDS: DateTime.TIME_24_WITH_SECONDS,
    TIME_WITH_SECONDS: DateTime.TIME_WITH_SECONDS,
  };
