import { BlogPost } from "../models";

export const blogPostsListFixtures: BlogPost[] = [
  {
    _id: "1",
    title: "Blog Post 1",
    slug: "blog-post-1",
    isPublished: true,
    publicationDate: new Date(),
    content: "This is the content of the first blog post",
    tags: ["Tag 1", "Tag 2"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    _id: "2",
    title: "Blog Post 2",
    slug: "blog-post-2",
    isPublished: true,
    publicationDate: new Date("2025-01-02"),
    content: "This is the content of the second blog post",
    tags: ["Tag 3", "Tag 4"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-02"),
  },
  {
    _id: "3",
    title: "Blog Post 3",
    slug: "blog-post-3",
    isPublished: true,
    publicationDate: new Date("2025-01-03"),
    content: "This is the content of the third blog post",
    tags: ["Tag 5", "Tag 6"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-03"),
  },
  {
    _id: "4",
    title: "Blog Post 4",
    slug: "blog-post-4",
    isPublished: true,
    publicationDate: new Date("2025-01-04"),
    content: "This is the content of the fourth blog post",
    tags: ["Tag 7", "Tag 8"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-04"),
  },
  {
    _id: "5",
    title: "Blog Post 5",
    slug: "blog-post-5",
    isPublished: true,
    publicationDate: new Date("2025-01-05"),
    content: "This is the content of the fifth blog post",
    tags: ["Tag 9", "Tag 10"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    _id: "6",
    title: "Blog Post 6",
    slug: "blog-post-6",
    isPublished: true,
    publicationDate: new Date("2025-01-06"),
    content: "This is the content of the sixth blog post",
    tags: ["Tag 11", "Tag 12"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date("2025-01-06"),
  },
  {
    _id: "7",
    title: "Blog Post 7",
    slug: "blog-post-7",
    isPublished: true,
    publicationDate: new Date("2025-01-07"),
    content: "This is the content of the seventh blog post",
    tags: ["Tag 13", "Tag 14"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-07"),
    updatedAt: new Date("2025-01-07"),
  },
  {
    _id: "8",
    title: "Blog Post 8",
    slug: "blog-post-8",
    isPublished: true,
    publicationDate: new Date("2025-01-08"),
    content: "This is the content of the eighth blog post",
    tags: ["Tag 15", "Tag 16"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-08"),
  },
  {
    _id: "9",
    title: "Blog Post 9",
    slug: "blog-post-9",
    isPublished: true,
    publicationDate: new Date("2025-01-09"),
    content: "This is the content of the ninth blog post",
    tags: ["Tag 17", "Tag 18"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-09"),
    updatedAt: new Date("2025-01-09"),
  },
  {
    _id: "10",
    title: "Blog Post 10",
    slug: "blog-post-10",
    isPublished: true,
    publicationDate: new Date("2025-01-10"),
    content: "This is the content of the tenth blog post",
    tags: ["Tag 19", "Tag 20"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    _id: "11",
    title: "Blog Post 11",
    slug: "blog-post-11",
    isPublished: true,
    publicationDate: new Date("2025-01-11"),
    content: "This is the content of the eleventh blog post",
    tags: ["Tag 21", "Tag 22"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-11"),
    updatedAt: new Date("2025-01-11"),
  },
  {
    _id: "12",
    title: "Blog Post 12",
    slug: "blog-post-12",
    isPublished: true,
    publicationDate: new Date("2025-01-12"),
    content: "This is the content of the twelfth blog post",
    tags: ["Tag 23", "Tag 24"],
    companyId: "1",
    appId: "1",
    createdAt: new Date("2025-01-12"),
    updatedAt: new Date("2025-01-12"),
  },
];
