export const CUSTOMER_SESSION_COOKIE = "customer_session";

export const CUSTOMER_OTP_RESEND_COOLDOWN_SECONDS = 60;
export const CUSTOMER_OTP_MAX_REQUESTS = 5;
export const CUSTOMER_OTP_TTL_SECONDS =
  CUSTOMER_OTP_RESEND_COOLDOWN_SECONDS * CUSTOMER_OTP_MAX_REQUESTS;

export const CUSTOMER_SESSION_TTL_SECONDS = 60 * 60;
